const Zonesapi=[
{
    
    heading:"Northern Railway (NR)",
    imgsrc:[
        "../img/northern-zone.jpg",
        "../img/locoshedghaziabad.jpg",
        "../img/newdelhi.jpg",
        "../img/nrtourism.jpg",

    ],
    para1:"The Northern Railway (NR) is one of the 19 railway zones of India and the northernmost zone of the Indian Railways. It is headquartered at the Baroda House in New Delhi.",
    suheading1:"The five divisional headquarters are located at:",
    divisionhead:[
        "Ambala railway division at Ambala (Haryana).",
        "Delhi railway division at Delhi.",
        "Firozpur railway division at Firozpur (Punjab).",
        "Lucknow NR railway division at Lucknow (Uttar Pradesh).",
        "Moradabad railway division at Moradabad (Uttar Pradesh).",
    ],
    subheading2:"Loco sheds:",
    locoshed:[
        "Electric Loco Shed, Ghaziabad.",
        "Electric Loco Shed, Ludhiana.",
        "Electric Loco Shed, Saharanpur.",
        "Electric Loco Shed, Khanalampura.",
        "Diesel Loco Shed, Tughlakabad.",
        "Diesel Loco Shed, Ludhiana.",
        "Diesel Loco Shed, Lucknow.",
        "Diesel Loco Shed, Roza.",
        "Diesel Loco Shed, Alambagh.",
    ],
    subheading3:"Major stations:",
    majorstations:[
        "New Delhi Railway Station (NDLS): The main railway station of Delhi and one of the busiest in India, serving as a major hub for trains to and from northern India.",
        "Old Delhi Railway Station (DLI): Also located in Delhi, this station handles a significant number of trains and passengers.",
        "Kanpur Central (CNB): Situated in Kanpur, Uttar Pradesh, this is a major railway station in the Northern Railway Zone.",
        "Lucknow Charbagh Railway Station (LKO): Located in Lucknow, Uttar Pradesh, it's one of the most beautiful and historic railway stations in India.",
        "Amritsar Junction (ASR): Serving the city of Amritsar in Punjab, this station is well-known foits connection to the Golden Temple.",
        "Chandigarh Railway Station (CDG): The primary station serving the capital city of Punjab and Haryana, Chandigarh.",
        "Jammu Tawi (JAT): Located in Jammu, Jammu and Kashmir, this station serves as a gateway to the northernmost region of India.",
        "Haridwar Junction (HW): Situated in Haridwar, Uttarakhand, this station is a significant stop for pilgrims visiting the holy city.",
        "Varanasi Junction (BSB): Serving the spiritual city of Varanasi, Uttar Pradesh, this station is an important stop on the Northern Railway network.",
        "Agra Cantt (AGC): Located in Agra, Uttar Pradesh, this station is commonly used by tourists visiting the iconic Taj Mahal.",
        "Moradabad Junction (MB): Situated in Moradabad, Uttar Pradesh, this station is an important junction on the Northern Railway.",
        "Panipat Junction (PNP): Located in Panipat, Haryana, this station serves as a vital stop on the Delhi-Ambala railway line.",

    ],
    subheading4:"Tourism Importance:",
    tourism:"The Northern Railway (NR) zone of India holds immense tourism importance as it connects travelers to a plethora of captivating destinations rich in history, culture, spirituality, and natural beauty. With its expansive network, NR enables tourists to explore iconic sites such as Delhi's India Gate and Red Fort, Agra's world-renowned Taj Mahal, Jaipur's stunning Hawa Mahal and Amer Fort, and the spiritual magnetism of Amritsar's Golden Temple. The zone extends its reach to the tranquil ghats of Haridwar and Rishikesh, the picturesque hill stations of Uttarakhand, the serene landscapes of Shimla via the Kalka-Shimla Railway, and the spiritual heart of Varanasi on the banks of the Ganges. Furthermore, NR provides access to the revered Vaishno Devi shrine in Katra, the charming cityscape of Chandigarh, and the historic and religious sites of Punjab. With its well-connected railway stations, NR serves as a gateway to these remarkable destinations, making it an indispensable conduit for travelers seeking to immerse themselves in the diverse tapestry of northern India's heritage and culture.",
},
{
    heading:"North Central Railway (NCR):",
    imgsrc:[
        "../img/northern-zone.jpg",
        "../img/locoshedghaziabad.jpg",
        "../img/newdelhi.jpg",
        "../img/nrtourism.jpg",

    ],
    para1:"The North Central Railway is one of the 19 railway zones in India. The largest railway station in NCR is Kanpur Central. It is headquartered at Prayagraj.",
    subheading1:"Serving the heartland of India, the North Central Railways comprises the following three divisions:",
    divisionhead:[
        "Allahabad railway division.",
        "Jhansi railway division.",
        "Agra railway division.",
    ],
    subheading2:"Loco sheds:",
    locoshed:[
        "Electric Loco Shed, Kanpur.",
        "Electric Loco Shed, Jhansi.",
        "Diesel Loco Shed, Jhansi.",
    ],
    subheading3:"Major stations:",
    majorstations:[
        "Prayagraj Junction (Allahabad Junction) - Uttar Pradesh",
        "Jhansi Junction - Uttar Pradesh",
        "Agra Cantt - Uttar Pradesh",
        "Gwalior Junction - Madhya Pradesh",
        "Kanpur Central - Uttar Pradesh",
        "Mathura Junction - Uttar Pradesh",
        "Tundla Junction - Uttar Pradesh",
        "Fatehpur - Uttar Pradesh",
        "Orai - Uttar Pradesh",
        "Banda Junction - Uttar Pradesh",
        "Etawah Junction - Uttar Pradesh",
        "Lalitpur - Uttar Pradesh",
        "Mahoba Junction - Uttar Pradesh",
        "Manikpur Junction - Uttar Pradesh",
        "Morena - Madhya Pradesh",
        "Barabanki Junction - Uttar Pradesh",
        "Itarsi Junction - Madhya Pradesh (It falls under the North Central Railway zone)",
    ],
    subheading4:"Tourism Importance:",
    tourism:"The Northern Central Railway (NCR) zone of India plays a significant role in promoting tourism by connecting travelers to a range of captivating destinations across its jurisdiction. With its extensive rail network, NCR enables tourists to explore diverse attractions in Uttar Pradesh and parts of neighboring states. The zone's pivotal stations such as Agra Cantt offer access to the iconic Taj Mahal and Agra Fort, both UNESCO World Heritage Sites. Varanasi Junction provides a gateway to the spiritual and cultural richness of Varanasi, with its ancient ghats and religious ceremonies along the Ganges River. Lucknow Charbagh Junction opens doors to the historical charm of Lucknow, known for its architectural heritage and cultural heritage.Furthermore, the NCR zone connects visitors to the serene beauty of Allahabad, the religious significance of Ayodhya, the historical allure of Jhansi, and the architectural marvels of Kanpur. These stations act as links to numerous other attractions, including Chitrakoot, a revered pilgrimage site, and the historically significant Gwalior. NCR's efficient rail services not only facilitate convenient travel but also contribute to the growth of local economies in these tourism-centric regions. With its strategic location and connectivity, NCR plays a pivotal role in welcoming travelers to explore the cultural, historical, and spiritual treasures of northern and central India.",
},
];
export default Zonesapi;